title: Scribbles By Sammy
description: A website with a blog
footer_text: Copyright 2021 Samanatha L
header_feature_image: ../uploads/article10-headerimage.jpg
header_text: Musings on Literature and Media
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
